{
  "name": "Colorado_MV_Sales",
  "compatibilityLevel": 1606,
  "model": {
    "culture": "en-US",
    "sourceQueryCulture": "en-US",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "expressions": [
      {
        "name": "DataFolder",
        "kind": "m",
        "expression": [
          "\"C:\\Users\\Asus\\Documents\\Colorado_PowerBI_Dashboard\\data\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]"
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sales",
        "columns": [
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "summarizeBy": "none",
            "formatString": "0"
          },
          {
            "name": "Quarter No",
            "dataType": "int64",
            "sourceColumn": "Quarter No",
            "summarizeBy": "none",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "County",
            "dataType": "string",
            "sourceColumn": "County",
            "summarizeBy": "none"
          },
          {
            "name": "Sales",
            "dataType": "int64",
            "sourceColumn": "Sales",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Period",
            "dataType": "string",
            "sourceColumn": "Period",
            "summarizeBy": "none",
            "sortByColumn": "Period Sort"
          },
          {
            "name": "Period Sort",
            "dataType": "int64",
            "sourceColumn": "Period Sort",
            "summarizeBy": "none",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Sales",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(DataFolder & \"\\colorado_motor_vehicle_sales.csv\"), [Delimiter = \",\", Columns = 4, Encoding = 65001, QuoteStyle = QuoteStyle.None]),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"year\", Int64.Type}, {\"quarter\", Int64.Type}, {\"county\", type text}, {\"sales\", Int64.Type}}),",
                "    Renamed = Table.RenameColumns(Typed, {{\"year\", \"Year\"}, {\"quarter\", \"Quarter No\"}, {\"county\", \"County\"}, {\"sales\", \"Sales\"}}),",
                "    AddDate = Table.AddColumn(Renamed, \"Date\", each #date([Year], ([Quarter No] - 1) * 3 + 1, 1), type date),",
                "    AddQ = Table.AddColumn(AddDate, \"Quarter\", each \"Q\" & Text.From([Quarter No]), type text),",
                "    AddPeriod = Table.AddColumn(AddQ, \"Period\", each Text.From([Year]) & \" Q\" & Text.From([Quarter No]), type text),",
                "    AddPeriodSort = Table.AddColumn(AddPeriod, \"Period Sort\", each [Year] * 10 + [Quarter No], Int64.Type),",
                "    AddRegion = Table.AddColumn(AddPeriodSort, \"Region\", each",
                "        if List.Contains({\"Adams\", \"Arapahoe\", \"Denver\", \"Douglas\", \"Jefferson\", \"Boulder\", \"Broomfield\", \"Boulder/Broomfield\"}, [County]) then \"Denver Metro\"",
                "        else if List.Contains({\"Larimer\", \"Weld\"}, [County]) then \"N. Front Range\"",
                "        else if List.Contains({\"El Paso\", \"Pueblo\", \"Fremont\"}, [County]) then \"S. Front Range\"",
                "        else if List.Contains({\"Mesa\", \"Garfield\", \"La Plata\"}, [County]) then \"Western Slope\"",
                "        else \"Rest of State\", type text)",
                "in",
                "    AddRegion"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Total Sales",
            "expression": "SUM ( Sales[Sales] )",
            "formatString": "$#,0"
          },
          {
            "name": "Total Sales (B)",
            "expression": "DIVIDE ( [Total Sales], 1000000000 )",
            "formatString": "$#,0.00\"B\""
          },
          {
            "name": "Sales $B",
            "expression": "DIVIDE ( [Total Sales], 1000000000 )",
            "formatString": "$#,0.0\"B\""
          },
          {
            "name": "Sales $M",
            "expression": "DIVIDE ( [Total Sales], 1000000 )",
            "formatString": "$#,0.0\"M\""
          },
          {
            "name": "Sales PY",
            "expression": "CALCULATE ( [Total Sales], SAMEPERIODLASTYEAR ( 'Calendar'[Date] ) )",
            "formatString": "$#,0"
          },
          {
            "name": "Sales PY $B",
            "expression": "DIVIDE ( [Sales PY], 1000000000 )",
            "formatString": "$#,0.0\"B\""
          },
          {
            "name": "YoY %",
            "expression": "DIVIDE ( [Total Sales] - [Sales PY], [Sales PY] )",
            "formatString": "0.0%"
          },
          {
            "name": "Sales PQ",
            "expression": "CALCULATE ( [Total Sales], DATEADD ( 'Calendar'[Date], -1, QUARTER ) )",
            "formatString": "$#,0"
          },
          {
            "name": "QoQ %",
            "expression": "DIVIDE ( [Total Sales] - [Sales PQ], [Sales PQ] )",
            "formatString": "0.0%"
          },
          {
            "name": "Rolling 4Q Sales $B",
            "expression": "VAR w = DATESINPERIOD ( 'Calendar'[Date], MAX ( 'Calendar'[Date] ), -1, YEAR ) VAR q = CALCULATE ( DISTINCTCOUNT ( Sales[Period Sort] ), w ) RETURN IF ( q = 4, CALCULATE ( [Sales $B], w ) )",
            "formatString": "$#,0.0\"B\""
          },
          {
            "name": "Quarters",
            "expression": "DISTINCTCOUNT ( Sales[Period Sort] )",
            "formatString": "#,0"
          },
          {
            "name": "Rows",
            "expression": "COUNTROWS ( Sales )",
            "formatString": "#,0"
          },
          {
            "name": "Avg Quarterly Sales",
            "expression": "DIVIDE ( [Total Sales], [Quarters] * 1000000000 )",
            "formatString": "$#,0.00\"B\""
          },
          {
            "name": "Latest Year",
            "expression": "MAX ( Sales[Year] )",
            "formatString": "0"
          },
          {
            "name": "First Year",
            "expression": "MIN ( Sales[Year] )",
            "formatString": "0"
          },
          {
            "name": "Latest Year Sales",
            "expression": "VAR y = [Latest Year] RETURN DIVIDE ( CALCULATE ( [Total Sales], Sales[Year] = y ), 1000000000 )",
            "formatString": "$#,0.00\"B\""
          },
          {
            "name": "Prior Year Sales",
            "expression": "VAR y = [Latest Year] - 1 RETURN DIVIDE ( CALCULATE ( [Total Sales], Sales[Year] = y ), 1000000000 )",
            "formatString": "$#,0.00\"B\""
          },
          {
            "name": "Latest YoY %",
            "expression": "DIVIDE ( [Latest Year Sales] - [Prior Year Sales], [Prior Year Sales] )",
            "formatString": "0.0%"
          },
          {
            "name": "CAGR",
            "expression": "VAR y1 = [First Year] VAR y2 = [Latest Year] VAR s1 = CALCULATE ( [Total Sales], Sales[Year] = y1 ) VAR s2 = CALCULATE ( [Total Sales], Sales[Year] = y2 ) RETURN IF ( y2 > y1 && s1 > 0, DIVIDE ( s2, s1 ) ^ ( 1 / ( y2 - y1 ) ) - 1 )",
            "formatString": "0.0%"
          },
          {
            "name": "Best Quarter Sales",
            "expression": "DIVIDE ( MAXX ( VALUES ( Sales[Period] ), [Total Sales] ), 1000000000 )",
            "formatString": "$#,0.00\"B\""
          },
          {
            "name": "Best Quarter",
            "expression": "MAXX ( TOPN ( 1, VALUES ( Sales[Period] ), [Total Sales] ), Sales[Period] )"
          },
          {
            "name": "Counties",
            "expression": "DISTINCTCOUNT ( Sales[County] )",
            "formatString": "#,0"
          },
          {
            "name": "Years",
            "expression": "DISTINCTCOUNT ( Sales[Year] )",
            "formatString": "#,0"
          },
          {
            "name": "Top County",
            "expression": "MAXX ( TOPN ( 1, VALUES ( Sales[County] ), [Total Sales] ), Sales[County] )"
          },
          {
            "name": "Top County Share",
            "expression": "DIVIDE ( MAXX ( VALUES ( Sales[County] ), [Total Sales] ), [Total Sales] )",
            "formatString": "0.0%"
          },
          {
            "name": "Share of State %",
            "expression": "DIVIDE ( [Total Sales], CALCULATE ( [Total Sales], REMOVEFILTERS ( Sales[County], Sales[Region] ) ) )",
            "formatString": "0.0%"
          },
          {
            "name": "Share of Year %",
            "expression": "DIVIDE ( [Total Sales], CALCULATE ( [Total Sales], REMOVEFILTERS ( 'Calendar'[Quarter], 'Calendar'[Quarter No], Sales[Quarter], Sales[Quarter No] ) ) )",
            "formatString": "0.0%"
          },
          {
            "name": "KPI Total Sales Sub",
            "expression": "IF ( ISBLANK ( [CAGR] ), \"single year selected\", ( IF ( [CAGR] >= 0, \"▲ \", \"▼ \" ) & FORMAT ( ABS ( [CAGR] ), \"0.0%\" ) & \" CAGR FY\" & RIGHT ( [First Year], 2 ) & \"–\" & RIGHT ( [Latest Year], 2 ) ) )"
          },
          {
            "name": "KPI Latest Year Sub",
            "expression": "IF ( ISBLANK ( [Latest YoY %] ), \"no prior year in selection\", ( IF ( [Latest YoY %] >= 0, \"▲ \", \"▼ \" ) & FORMAT ( ABS ( [Latest YoY %] ), \"0.0%\" ) & \" vs FY\" & ( [Latest Year] - 1 ) ) )"
          },
          {
            "name": "KPI Avg Quarter Sub",
            "expression": "\"across \" & [Quarters] & \" quarters\""
          },
          {
            "name": "KPI Best Quarter Sub",
            "expression": "\"peak quarter: \" & [Best Quarter]"
          },
          {
            "name": "KPI Top County Sub",
            "expression": "FORMAT ( [Top County Share], \"0.0%\" ) & \" share of sales\""
          },
          {
            "name": "KPI Counties Sub",
            "expression": "[Years] & \" years · \" & [Quarters] & \" quarters\""
          },
          {
            "name": "Delta Color CAGR",
            "expression": "IF ( [CAGR] >= 0, \"#0CA30C\", \"#D03B3B\" )"
          },
          {
            "name": "Delta Color YoY",
            "expression": "IF ( [Latest YoY %] >= 0, \"#0CA30C\", \"#D03B3B\" )"
          },
          {
            "name": "YoY Bar Color",
            "expression": "IF ( [YoY %] >= 0, \"#0CA30C\", \"#D03B3B\" )"
          },
          {
            "name": "QoQ Bar Color",
            "expression": "IF ( [QoQ %] >= 0, \"#0CA30C\", \"#D03B3B\" )"
          },
          {
            "name": "CAGR Bar Color",
            "expression": "IF ( [CAGR] >= 0, \"#0CA30C\", \"#D03B3B\" )"
          }
        ]
      },
      {
        "name": "Calendar",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd",
            "isKey": true
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "summarizeBy": "none",
            "formatString": "0"
          },
          {
            "name": "Quarter No",
            "dataType": "int64",
            "sourceColumn": "Quarter No",
            "summarizeBy": "none",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Year Quarter",
            "dataType": "string",
            "sourceColumn": "Year Quarter",
            "summarizeBy": "none",
            "sortByColumn": "Year Quarter Sort"
          },
          {
            "name": "Year Quarter Sort",
            "dataType": "int64",
            "sourceColumn": "Year Quarter Sort",
            "summarizeBy": "none",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Fiscal Year",
            "dataType": "string",
            "sourceColumn": "Fiscal Year",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter Start",
            "dataType": "dateTime",
            "sourceColumn": "Quarter Start",
            "summarizeBy": "none",
            "formatString": "mmm yyyy"
          }
        ],
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Dates = List.Dates(#date(2008, 1, 1), Duration.Days(#date(2015, 12, 31) - #date(2008, 1, 1)) + 1, #duration(1, 0, 0, 0)),",
                "    T = Table.FromList(Dates, Splitter.SplitByNothing(), {\"Date\"}),",
                "    T1 = Table.TransformColumnTypes(T, {{\"Date\", type date}}),",
                "    T2 = Table.AddColumn(T1, \"Year\", each Date.Year([Date]), Int64.Type),",
                "    T3 = Table.AddColumn(T2, \"Quarter No\", each Date.QuarterOfYear([Date]), Int64.Type),",
                "    T4 = Table.AddColumn(T3, \"Quarter\", each \"Q\" & Text.From(Date.QuarterOfYear([Date])), type text),",
                "    T5 = Table.AddColumn(T4, \"Year Quarter\", each Text.From(Date.Year([Date])) & \" Q\" & Text.From(Date.QuarterOfYear([Date])), type text),",
                "    T6 = Table.AddColumn(T5, \"Year Quarter Sort\", each Date.Year([Date]) * 10 + Date.QuarterOfYear([Date]), Int64.Type),",
                "    T7 = Table.AddColumn(T6, \"Fiscal Year\", each \"FY\" & Text.From(Date.Year([Date])), type text),",
                "    T8 = Table.AddColumn(T7, \"Quarter Start\", each Date.StartOfQuarter([Date]), type date)",
                "in",
                "    T8"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "SalesToCalendar",
        "fromTable": "Sales",
        "fromColumn": "Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"DataFolder\",\"Sales\",\"Calendar\"]"
      }
    ]
  }
}